// Generated by gencpp from file deepbuilder/ex_read.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_EX_READ_H
#define DEEPBUILDER_MESSAGE_EX_READ_H

#include <ros/service_traits.h>


#include <deepbuilder/ex_readRequest.h>
#include <deepbuilder/ex_readResponse.h>


namespace deepbuilder
{

struct ex_read
{

typedef ex_readRequest Request;
typedef ex_readResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ex_read
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ex_read > {
  static const char* value()
  {
    return "7848c669d219de11243ab460d9130d88";
  }

  static const char* value(const ::deepbuilder::ex_read&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ex_read > {
  static const char* value()
  {
    return "deepbuilder/ex_read";
  }

  static const char* value(const ::deepbuilder::ex_read&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ex_readRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ex_read > 
template<>
struct MD5Sum< ::deepbuilder::ex_readRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ex_read >::value();
  }
  static const char* value(const ::deepbuilder::ex_readRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ex_readRequest> should match 
// service_traits::DataType< ::deepbuilder::ex_read > 
template<>
struct DataType< ::deepbuilder::ex_readRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ex_read >::value();
  }
  static const char* value(const ::deepbuilder::ex_readRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ex_readResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ex_read > 
template<>
struct MD5Sum< ::deepbuilder::ex_readResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ex_read >::value();
  }
  static const char* value(const ::deepbuilder::ex_readResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ex_readResponse> should match 
// service_traits::DataType< ::deepbuilder::ex_read > 
template<>
struct DataType< ::deepbuilder::ex_readResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ex_read >::value();
  }
  static const char* value(const ::deepbuilder::ex_readResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_EX_READ_H
