// Generated by gencpp from file deepbuilder/ex_write.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_EX_WRITE_H
#define DEEPBUILDER_MESSAGE_EX_WRITE_H

#include <ros/service_traits.h>


#include <deepbuilder/ex_writeRequest.h>
#include <deepbuilder/ex_writeResponse.h>


namespace deepbuilder
{

struct ex_write
{

typedef ex_writeRequest Request;
typedef ex_writeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ex_write
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ex_write > {
  static const char* value()
  {
    return "93beb009a54ccf54fefb5b85020d0e0d";
  }

  static const char* value(const ::deepbuilder::ex_write&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ex_write > {
  static const char* value()
  {
    return "deepbuilder/ex_write";
  }

  static const char* value(const ::deepbuilder::ex_write&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ex_writeRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ex_write > 
template<>
struct MD5Sum< ::deepbuilder::ex_writeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ex_write >::value();
  }
  static const char* value(const ::deepbuilder::ex_writeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ex_writeRequest> should match 
// service_traits::DataType< ::deepbuilder::ex_write > 
template<>
struct DataType< ::deepbuilder::ex_writeRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ex_write >::value();
  }
  static const char* value(const ::deepbuilder::ex_writeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ex_writeResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ex_write > 
template<>
struct MD5Sum< ::deepbuilder::ex_writeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ex_write >::value();
  }
  static const char* value(const ::deepbuilder::ex_writeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ex_writeResponse> should match 
// service_traits::DataType< ::deepbuilder::ex_write > 
template<>
struct DataType< ::deepbuilder::ex_writeResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ex_write >::value();
  }
  static const char* value(const ::deepbuilder::ex_writeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_EX_WRITE_H
