// Generated by gencpp from file deepbuilder/ro_get_robot_stateResponse.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_GET_ROBOT_STATERESPONSE_H
#define DEEPBUILDER_MESSAGE_RO_GET_ROBOT_STATERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepbuilder
{
template <class ContainerAllocator>
struct ro_get_robot_stateResponse_
{
  typedef ro_get_robot_stateResponse_<ContainerAllocator> Type;

  ro_get_robot_stateResponse_()
    : joint_states()  {
    }
  ro_get_robot_stateResponse_(const ContainerAllocator& _alloc)
    : joint_states(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _joint_states_type;
  _joint_states_type joint_states;





  typedef boost::shared_ptr< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ro_get_robot_stateResponse_

typedef ::deepbuilder::ro_get_robot_stateResponse_<std::allocator<void> > ro_get_robot_stateResponse;

typedef boost::shared_ptr< ::deepbuilder::ro_get_robot_stateResponse > ro_get_robot_stateResponsePtr;
typedef boost::shared_ptr< ::deepbuilder::ro_get_robot_stateResponse const> ro_get_robot_stateResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'deepbuilder': ['/home/ros/deepbuilder/catkin_ws/src/deepbuilder/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4fa113d228950451cb528101719c77a1";
  }

  static const char* value(const ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4fa113d228950451ULL;
  static const uint64_t static_value2 = 0xcb528101719c77a1ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/ro_get_robot_stateResponse";
  }

  static const char* value(const ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] joint_states\n\
";
  }

  static const char* value(const ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_states);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ro_get_robot_stateResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::ro_get_robot_stateResponse_<ContainerAllocator>& v)
  {
    s << indent << "joint_states[]" << std::endl;
    for (size_t i = 0; i < v.joint_states.size(); ++i)
    {
      s << indent << "  joint_states[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.joint_states[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_GET_ROBOT_STATERESPONSE_H
