// Generated by gencpp from file deepbuilder/ro_gripper_setforceRequest.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_GRIPPER_SETFORCEREQUEST_H
#define DEEPBUILDER_MESSAGE_RO_GRIPPER_SETFORCEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepbuilder
{
template <class ContainerAllocator>
struct ro_gripper_setforceRequest_
{
  typedef ro_gripper_setforceRequest_<ContainerAllocator> Type;

  ro_gripper_setforceRequest_()
    : force(0)  {
    }
  ro_gripper_setforceRequest_(const ContainerAllocator& _alloc)
    : force(0)  {
  (void)_alloc;
    }



   typedef int32_t _force_type;
  _force_type force;





  typedef boost::shared_ptr< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ro_gripper_setforceRequest_

typedef ::deepbuilder::ro_gripper_setforceRequest_<std::allocator<void> > ro_gripper_setforceRequest;

typedef boost::shared_ptr< ::deepbuilder::ro_gripper_setforceRequest > ro_gripper_setforceRequestPtr;
typedef boost::shared_ptr< ::deepbuilder::ro_gripper_setforceRequest const> ro_gripper_setforceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'deepbuilder': ['/home/ros/deepbuilder/catkin_ws/src/deepbuilder/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20fe3739baa02e749c8913cd441870f0";
  }

  static const char* value(const ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20fe3739baa02e74ULL;
  static const uint64_t static_value2 = 0x9c8913cd441870f0ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/ro_gripper_setforceRequest";
  }

  static const char* value(const ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 force\n\
";
  }

  static const char* value(const ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.force);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ro_gripper_setforceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::ro_gripper_setforceRequest_<ContainerAllocator>& v)
  {
    s << indent << "force: ";
    Printer<int32_t>::stream(s, indent + "  ", v.force);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_GRIPPER_SETFORCEREQUEST_H
