// Generated by gencpp from file deepbuilder/ro_get_state.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_GET_STATE_H
#define DEEPBUILDER_MESSAGE_RO_GET_STATE_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_get_stateRequest.h>
#include <deepbuilder/ro_get_stateResponse.h>


namespace deepbuilder
{

struct ro_get_state
{

typedef ro_get_stateRequest Request;
typedef ro_get_stateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_get_state
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_get_state > {
  static const char* value()
  {
    return "d02bed547f95931d877d3048b2328dcb";
  }

  static const char* value(const ::deepbuilder::ro_get_state&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_get_state > {
  static const char* value()
  {
    return "deepbuilder/ro_get_state";
  }

  static const char* value(const ::deepbuilder::ro_get_state&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_get_stateRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_get_state > 
template<>
struct MD5Sum< ::deepbuilder::ro_get_stateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_get_state >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_stateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_get_stateRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_get_state > 
template<>
struct DataType< ::deepbuilder::ro_get_stateRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_get_state >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_stateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_get_stateResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_get_state > 
template<>
struct MD5Sum< ::deepbuilder::ro_get_stateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_get_state >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_stateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_get_stateResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_get_state > 
template<>
struct DataType< ::deepbuilder::ro_get_stateResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_get_state >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_stateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_GET_STATE_H
