// Generated by gencpp from file deepbuilder/ro_gripper_setspeed.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_GRIPPER_SETSPEED_H
#define DEEPBUILDER_MESSAGE_RO_GRIPPER_SETSPEED_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_gripper_setspeedRequest.h>
#include <deepbuilder/ro_gripper_setspeedResponse.h>


namespace deepbuilder
{

struct ro_gripper_setspeed
{

typedef ro_gripper_setspeedRequest Request;
typedef ro_gripper_setspeedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_gripper_setspeed
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_gripper_setspeed > {
  static const char* value()
  {
    return "53122cc92cfbc917935bb064451b2b06";
  }

  static const char* value(const ::deepbuilder::ro_gripper_setspeed&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_gripper_setspeed > {
  static const char* value()
  {
    return "deepbuilder/ro_gripper_setspeed";
  }

  static const char* value(const ::deepbuilder::ro_gripper_setspeed&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_gripper_setspeedRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_gripper_setspeed > 
template<>
struct MD5Sum< ::deepbuilder::ro_gripper_setspeedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_gripper_setspeed >::value();
  }
  static const char* value(const ::deepbuilder::ro_gripper_setspeedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_gripper_setspeedRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_gripper_setspeed > 
template<>
struct DataType< ::deepbuilder::ro_gripper_setspeedRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_gripper_setspeed >::value();
  }
  static const char* value(const ::deepbuilder::ro_gripper_setspeedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_gripper_setspeedResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_gripper_setspeed > 
template<>
struct MD5Sum< ::deepbuilder::ro_gripper_setspeedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_gripper_setspeed >::value();
  }
  static const char* value(const ::deepbuilder::ro_gripper_setspeedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_gripper_setspeedResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_gripper_setspeed > 
template<>
struct DataType< ::deepbuilder::ro_gripper_setspeedResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_gripper_setspeed >::value();
  }
  static const char* value(const ::deepbuilder::ro_gripper_setspeedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_GRIPPER_SETSPEED_H
