// Generated by gencpp from file deepbuilder/ro_get_joint_states.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_GET_JOINT_STATES_H
#define DEEPBUILDER_MESSAGE_RO_GET_JOINT_STATES_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_get_joint_statesRequest.h>
#include <deepbuilder/ro_get_joint_statesResponse.h>


namespace deepbuilder
{

struct ro_get_joint_states
{

typedef ro_get_joint_statesRequest Request;
typedef ro_get_joint_statesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_get_joint_states
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_get_joint_states > {
  static const char* value()
  {
    return "482cc7b23f4d6ca5e5aac26ecce1ce01";
  }

  static const char* value(const ::deepbuilder::ro_get_joint_states&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_get_joint_states > {
  static const char* value()
  {
    return "deepbuilder/ro_get_joint_states";
  }

  static const char* value(const ::deepbuilder::ro_get_joint_states&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_get_joint_statesRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_get_joint_states > 
template<>
struct MD5Sum< ::deepbuilder::ro_get_joint_statesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_get_joint_states >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_joint_statesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_get_joint_statesRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_get_joint_states > 
template<>
struct DataType< ::deepbuilder::ro_get_joint_statesRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_get_joint_states >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_joint_statesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_get_joint_statesResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_get_joint_states > 
template<>
struct MD5Sum< ::deepbuilder::ro_get_joint_statesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_get_joint_states >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_joint_statesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_get_joint_statesResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_get_joint_states > 
template<>
struct DataType< ::deepbuilder::ro_get_joint_statesResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_get_joint_states >::value();
  }
  static const char* value(const ::deepbuilder::ro_get_joint_statesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_GET_JOINT_STATES_H
