// Generated by gencpp from file deepbuilder/ro_move_cam.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_MOVE_CAM_H
#define DEEPBUILDER_MESSAGE_RO_MOVE_CAM_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_move_camRequest.h>
#include <deepbuilder/ro_move_camResponse.h>


namespace deepbuilder
{

struct ro_move_cam
{

typedef ro_move_camRequest Request;
typedef ro_move_camResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_move_cam
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_move_cam > {
  static const char* value()
  {
    return "65f9af88059b07caeeaf7e2d659e542b";
  }

  static const char* value(const ::deepbuilder::ro_move_cam&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_move_cam > {
  static const char* value()
  {
    return "deepbuilder/ro_move_cam";
  }

  static const char* value(const ::deepbuilder::ro_move_cam&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_move_camRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_move_cam > 
template<>
struct MD5Sum< ::deepbuilder::ro_move_camRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_move_cam >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_camRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_move_camRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_move_cam > 
template<>
struct DataType< ::deepbuilder::ro_move_camRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_move_cam >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_camRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_move_camResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_move_cam > 
template<>
struct MD5Sum< ::deepbuilder::ro_move_camResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_move_cam >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_camResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_move_camResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_move_cam > 
template<>
struct DataType< ::deepbuilder::ro_move_camResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_move_cam >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_camResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_MOVE_CAM_H
