// Generated by gencpp from file deepbuilder/ro_move_point.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_MOVE_POINT_H
#define DEEPBUILDER_MESSAGE_RO_MOVE_POINT_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_move_pointRequest.h>
#include <deepbuilder/ro_move_pointResponse.h>


namespace deepbuilder
{

struct ro_move_point
{

typedef ro_move_pointRequest Request;
typedef ro_move_pointResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_move_point
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_move_point > {
  static const char* value()
  {
    return "9b6f685fe107ffd37a5665d7b368a641";
  }

  static const char* value(const ::deepbuilder::ro_move_point&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_move_point > {
  static const char* value()
  {
    return "deepbuilder/ro_move_point";
  }

  static const char* value(const ::deepbuilder::ro_move_point&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_move_pointRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_move_point > 
template<>
struct MD5Sum< ::deepbuilder::ro_move_pointRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_move_point >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pointRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_move_pointRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_move_point > 
template<>
struct DataType< ::deepbuilder::ro_move_pointRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_move_point >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pointRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_move_pointResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_move_point > 
template<>
struct MD5Sum< ::deepbuilder::ro_move_pointResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_move_point >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pointResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_move_pointResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_move_point > 
template<>
struct DataType< ::deepbuilder::ro_move_pointResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_move_point >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pointResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_MOVE_POINT_H
