// Generated by gencpp from file deepbuilder/ro_move_pointRequest.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_MOVE_POINTREQUEST_H
#define DEEPBUILDER_MESSAGE_RO_MOVE_POINTREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepbuilder
{
template <class ContainerAllocator>
struct ro_move_pointRequest_
{
  typedef ro_move_pointRequest_<ContainerAllocator> Type;

  ro_move_pointRequest_()
    : goal()
    , speed(0.0)  {
    }
  ro_move_pointRequest_(const ContainerAllocator& _alloc)
    : goal(_alloc)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _goal_type;
  _goal_type goal;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ro_move_pointRequest_

typedef ::deepbuilder::ro_move_pointRequest_<std::allocator<void> > ro_move_pointRequest;

typedef boost::shared_ptr< ::deepbuilder::ro_move_pointRequest > ro_move_pointRequestPtr;
typedef boost::shared_ptr< ::deepbuilder::ro_move_pointRequest const> ro_move_pointRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'deepbuilder': ['/home/ros/deepbuilder/catkin_ws/src/deepbuilder/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2e0655060714c46e883f8bd4da7a9873";
  }

  static const char* value(const ::deepbuilder::ro_move_pointRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2e0655060714c46eULL;
  static const uint64_t static_value2 = 0x883f8bd4da7a9873ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/ro_move_pointRequest";
  }

  static const char* value(const ::deepbuilder::ro_move_pointRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] goal\n\
float32 speed\n\
";
  }

  static const char* value(const ::deepbuilder::ro_move_pointRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ro_move_pointRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::ro_move_pointRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::ro_move_pointRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal[]" << std::endl;
    for (size_t i = 0; i < v.goal.size(); ++i)
    {
      s << indent << "  goal[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.goal[i]);
    }
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_MOVE_POINTREQUEST_H
