// Generated by gencpp from file deepbuilder/ro_move_path.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_MOVE_PATH_H
#define DEEPBUILDER_MESSAGE_RO_MOVE_PATH_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_move_pathRequest.h>
#include <deepbuilder/ro_move_pathResponse.h>


namespace deepbuilder
{

struct ro_move_path
{

typedef ro_move_pathRequest Request;
typedef ro_move_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_move_path
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_move_path > {
  static const char* value()
  {
    return "8c34125c1c77b9e671e5d9698ccd6432";
  }

  static const char* value(const ::deepbuilder::ro_move_path&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_move_path > {
  static const char* value()
  {
    return "deepbuilder/ro_move_path";
  }

  static const char* value(const ::deepbuilder::ro_move_path&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_move_pathRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_move_path > 
template<>
struct MD5Sum< ::deepbuilder::ro_move_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_move_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_move_pathRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_move_path > 
template<>
struct DataType< ::deepbuilder::ro_move_pathRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_move_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_move_pathResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_move_path > 
template<>
struct MD5Sum< ::deepbuilder::ro_move_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_move_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_move_pathResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_move_path > 
template<>
struct DataType< ::deepbuilder::ro_move_pathResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_move_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_move_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_MOVE_PATH_H
