// Generated by gencpp from file deepbuilder/ro_plan_cartesian.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_PLAN_CARTESIAN_H
#define DEEPBUILDER_MESSAGE_RO_PLAN_CARTESIAN_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_plan_cartesianRequest.h>
#include <deepbuilder/ro_plan_cartesianResponse.h>


namespace deepbuilder
{

struct ro_plan_cartesian
{

typedef ro_plan_cartesianRequest Request;
typedef ro_plan_cartesianResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_plan_cartesian
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_plan_cartesian > {
  static const char* value()
  {
    return "baeeb75638ee6d1bdbcd79638e421c05";
  }

  static const char* value(const ::deepbuilder::ro_plan_cartesian&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_plan_cartesian > {
  static const char* value()
  {
    return "deepbuilder/ro_plan_cartesian";
  }

  static const char* value(const ::deepbuilder::ro_plan_cartesian&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_plan_cartesianRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_plan_cartesian > 
template<>
struct MD5Sum< ::deepbuilder::ro_plan_cartesianRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_plan_cartesian >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_cartesianRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_plan_cartesianRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_plan_cartesian > 
template<>
struct DataType< ::deepbuilder::ro_plan_cartesianRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_plan_cartesian >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_cartesianRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_plan_cartesianResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_plan_cartesian > 
template<>
struct MD5Sum< ::deepbuilder::ro_plan_cartesianResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_plan_cartesian >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_cartesianResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_plan_cartesianResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_plan_cartesian > 
template<>
struct DataType< ::deepbuilder::ro_plan_cartesianResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_plan_cartesian >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_cartesianResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_PLAN_CARTESIAN_H
