// Generated by gencpp from file deepbuilder/ro_plan_path.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_PLAN_PATH_H
#define DEEPBUILDER_MESSAGE_RO_PLAN_PATH_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_plan_pathRequest.h>
#include <deepbuilder/ro_plan_pathResponse.h>


namespace deepbuilder
{

struct ro_plan_path
{

typedef ro_plan_pathRequest Request;
typedef ro_plan_pathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_plan_path
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_plan_path > {
  static const char* value()
  {
    return "6bb18060add6f8092d505a812c13f49f";
  }

  static const char* value(const ::deepbuilder::ro_plan_path&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_plan_path > {
  static const char* value()
  {
    return "deepbuilder/ro_plan_path";
  }

  static const char* value(const ::deepbuilder::ro_plan_path&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_plan_pathRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_plan_path > 
template<>
struct MD5Sum< ::deepbuilder::ro_plan_pathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_plan_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_pathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_plan_pathRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_plan_path > 
template<>
struct DataType< ::deepbuilder::ro_plan_pathRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_plan_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_pathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_plan_pathResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_plan_path > 
template<>
struct MD5Sum< ::deepbuilder::ro_plan_pathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_plan_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_pathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_plan_pathResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_plan_path > 
template<>
struct DataType< ::deepbuilder::ro_plan_pathResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_plan_path >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_pathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_PLAN_PATH_H
