// Generated by gencpp from file deepbuilder/ro_plan_motion.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_PLAN_MOTION_H
#define DEEPBUILDER_MESSAGE_RO_PLAN_MOTION_H

#include <ros/service_traits.h>


#include <deepbuilder/ro_plan_motionRequest.h>
#include <deepbuilder/ro_plan_motionResponse.h>


namespace deepbuilder
{

struct ro_plan_motion
{

typedef ro_plan_motionRequest Request;
typedef ro_plan_motionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ro_plan_motion
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::ro_plan_motion > {
  static const char* value()
  {
    return "79a5a45e866664a192667e3d0dcdaa5f";
  }

  static const char* value(const ::deepbuilder::ro_plan_motion&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::ro_plan_motion > {
  static const char* value()
  {
    return "deepbuilder/ro_plan_motion";
  }

  static const char* value(const ::deepbuilder::ro_plan_motion&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::ro_plan_motionRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_plan_motion > 
template<>
struct MD5Sum< ::deepbuilder::ro_plan_motionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_plan_motion >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_motionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_plan_motionRequest> should match 
// service_traits::DataType< ::deepbuilder::ro_plan_motion > 
template<>
struct DataType< ::deepbuilder::ro_plan_motionRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_plan_motion >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_motionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::ro_plan_motionResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::ro_plan_motion > 
template<>
struct MD5Sum< ::deepbuilder::ro_plan_motionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::ro_plan_motion >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_motionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::ro_plan_motionResponse> should match 
// service_traits::DataType< ::deepbuilder::ro_plan_motion > 
template<>
struct DataType< ::deepbuilder::ro_plan_motionResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::ro_plan_motion >::value();
  }
  static const char* value(const ::deepbuilder::ro_plan_motionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_PLAN_MOTION_H
