// Generated by gencpp from file deepbuilder/ro_plan_pathRequest.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RO_PLAN_PATHREQUEST_H
#define DEEPBUILDER_MESSAGE_RO_PLAN_PATHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepbuilder
{
template <class ContainerAllocator>
struct ro_plan_pathRequest_
{
  typedef ro_plan_pathRequest_<ContainerAllocator> Type;

  ro_plan_pathRequest_()
    : goal_pose()
    , state_pose()
    , session()
    , speed(0.0)
    , state_mesh_vertices()
    , state_mesh_indices()  {
    }
  ro_plan_pathRequest_(const ContainerAllocator& _alloc)
    : goal_pose(_alloc)
    , state_pose(_alloc)
    , session(_alloc)
    , speed(0.0)
    , state_mesh_vertices(_alloc)
    , state_mesh_indices(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _goal_pose_type;
  _goal_pose_type goal_pose;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _state_pose_type;
  _state_pose_type state_pose;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _session_type;
  _session_type session;

   typedef float _speed_type;
  _speed_type speed;

   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _state_mesh_vertices_type;
  _state_mesh_vertices_type state_mesh_vertices;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _state_mesh_indices_type;
  _state_mesh_indices_type state_mesh_indices;





  typedef boost::shared_ptr< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> const> ConstPtr;

}; // struct ro_plan_pathRequest_

typedef ::deepbuilder::ro_plan_pathRequest_<std::allocator<void> > ro_plan_pathRequest;

typedef boost::shared_ptr< ::deepbuilder::ro_plan_pathRequest > ro_plan_pathRequestPtr;
typedef boost::shared_ptr< ::deepbuilder::ro_plan_pathRequest const> ro_plan_pathRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0215280a600c325b1ce7ede7a8b5184a";
  }

  static const char* value(const ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0215280a600c325bULL;
  static const uint64_t static_value2 = 0x1ce7ede7a8b5184aULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/ro_plan_pathRequest";
  }

  static const char* value(const ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] goal_pose\n\
float32[] state_pose\n\
string session\n\
float32 speed\n\
float32[] state_mesh_vertices\n\
int32[] state_mesh_indices\n\
";
  }

  static const char* value(const ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goal_pose);
      stream.next(m.state_pose);
      stream.next(m.session);
      stream.next(m.speed);
      stream.next(m.state_mesh_vertices);
      stream.next(m.state_mesh_indices);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ro_plan_pathRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::ro_plan_pathRequest_<ContainerAllocator>& v)
  {
    s << indent << "goal_pose[]" << std::endl;
    for (size_t i = 0; i < v.goal_pose.size(); ++i)
    {
      s << indent << "  goal_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.goal_pose[i]);
    }
    s << indent << "state_pose[]" << std::endl;
    for (size_t i = 0; i < v.state_pose.size(); ++i)
    {
      s << indent << "  state_pose[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.state_pose[i]);
    }
    s << indent << "session: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.session);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "state_mesh_vertices[]" << std::endl;
    for (size_t i = 0; i < v.state_mesh_vertices.size(); ++i)
    {
      s << indent << "  state_mesh_vertices[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.state_mesh_vertices[i]);
    }
    s << indent << "state_mesh_indices[]" << std::endl;
    for (size_t i = 0; i < v.state_mesh_indices.size(); ++i)
    {
      s << indent << "  state_mesh_indices[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.state_mesh_indices[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RO_PLAN_PATHREQUEST_H
