// Generated by gencpp from file deepbuilder/rt_is_ready.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RT_IS_READY_H
#define DEEPBUILDER_MESSAGE_RT_IS_READY_H

#include <ros/service_traits.h>


#include <deepbuilder/rt_is_readyRequest.h>
#include <deepbuilder/rt_is_readyResponse.h>


namespace deepbuilder
{

struct rt_is_ready
{

typedef rt_is_readyRequest Request;
typedef rt_is_readyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rt_is_ready
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::rt_is_ready > {
  static const char* value()
  {
    return "6f378c6311f9e6ccd2cd8c5b327003f1";
  }

  static const char* value(const ::deepbuilder::rt_is_ready&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::rt_is_ready > {
  static const char* value()
  {
    return "deepbuilder/rt_is_ready";
  }

  static const char* value(const ::deepbuilder::rt_is_ready&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::rt_is_readyRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::rt_is_ready > 
template<>
struct MD5Sum< ::deepbuilder::rt_is_readyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::rt_is_ready >::value();
  }
  static const char* value(const ::deepbuilder::rt_is_readyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::rt_is_readyRequest> should match 
// service_traits::DataType< ::deepbuilder::rt_is_ready > 
template<>
struct DataType< ::deepbuilder::rt_is_readyRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::rt_is_ready >::value();
  }
  static const char* value(const ::deepbuilder::rt_is_readyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::rt_is_readyResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::rt_is_ready > 
template<>
struct MD5Sum< ::deepbuilder::rt_is_readyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::rt_is_ready >::value();
  }
  static const char* value(const ::deepbuilder::rt_is_readyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::rt_is_readyResponse> should match 
// service_traits::DataType< ::deepbuilder::rt_is_ready > 
template<>
struct DataType< ::deepbuilder::rt_is_readyResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::rt_is_ready >::value();
  }
  static const char* value(const ::deepbuilder::rt_is_readyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RT_IS_READY_H
