// Generated by gencpp from file deepbuilder/rt_set_action.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RT_SET_ACTION_H
#define DEEPBUILDER_MESSAGE_RT_SET_ACTION_H

#include <ros/service_traits.h>


#include <deepbuilder/rt_set_actionRequest.h>
#include <deepbuilder/rt_set_actionResponse.h>


namespace deepbuilder
{

struct rt_set_action
{

typedef rt_set_actionRequest Request;
typedef rt_set_actionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct rt_set_action
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::rt_set_action > {
  static const char* value()
  {
    return "5d06ec287625f49b9001c48a2d24b856";
  }

  static const char* value(const ::deepbuilder::rt_set_action&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::rt_set_action > {
  static const char* value()
  {
    return "deepbuilder/rt_set_action";
  }

  static const char* value(const ::deepbuilder::rt_set_action&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::rt_set_actionRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::rt_set_action > 
template<>
struct MD5Sum< ::deepbuilder::rt_set_actionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::rt_set_action >::value();
  }
  static const char* value(const ::deepbuilder::rt_set_actionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::rt_set_actionRequest> should match 
// service_traits::DataType< ::deepbuilder::rt_set_action > 
template<>
struct DataType< ::deepbuilder::rt_set_actionRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::rt_set_action >::value();
  }
  static const char* value(const ::deepbuilder::rt_set_actionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::rt_set_actionResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::rt_set_action > 
template<>
struct MD5Sum< ::deepbuilder::rt_set_actionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::rt_set_action >::value();
  }
  static const char* value(const ::deepbuilder::rt_set_actionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::rt_set_actionResponse> should match 
// service_traits::DataType< ::deepbuilder::rt_set_action > 
template<>
struct DataType< ::deepbuilder::rt_set_actionResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::rt_set_action >::value();
  }
  static const char* value(const ::deepbuilder::rt_set_actionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RT_SET_ACTION_H
