// Generated by gencpp from file deepbuilder/rt_set_stateRequest.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RT_SET_STATEREQUEST_H
#define DEEPBUILDER_MESSAGE_RT_SET_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/state.h>

namespace deepbuilder
{
template <class ContainerAllocator>
struct rt_set_stateRequest_
{
  typedef rt_set_stateRequest_<ContainerAllocator> Type;

  rt_set_stateRequest_()
    : controller()
    , state()  {
    }
  rt_set_stateRequest_(const ContainerAllocator& _alloc)
    : controller(_alloc)
    , state(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _controller_type;
  _controller_type controller;

   typedef  ::my_msgs::state_<ContainerAllocator>  _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rt_set_stateRequest_

typedef ::deepbuilder::rt_set_stateRequest_<std::allocator<void> > rt_set_stateRequest;

typedef boost::shared_ptr< ::deepbuilder::rt_set_stateRequest > rt_set_stateRequestPtr;
typedef boost::shared_ptr< ::deepbuilder::rt_set_stateRequest const> rt_set_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'deepbuilder': ['/home/ros/deepbuilder/catkin_ws/src/deepbuilder/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32b4089e124a4eaa45ecb040a983b2cd";
  }

  static const char* value(const ::deepbuilder::rt_set_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32b4089e124a4eaaULL;
  static const uint64_t static_value2 = 0x45ecb040a983b2cdULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/rt_set_stateRequest";
  }

  static const char* value(const ::deepbuilder::rt_set_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string controller\n\
my_msgs/state state\n\
\n\
================================================================================\n\
MSG: my_msgs/state\n\
string action_id\n\
bool out_of_reach\n\
bool self_collision\n\
geometry_msgs/Pose last_tcp\n\
int32 fastest_box\n\
int32 highest_box\n\
float32 current_height\n\
geometry_msgs/Pose[] box_poses\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::deepbuilder::rt_set_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller);
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rt_set_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::rt_set_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::rt_set_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "controller: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.controller);
    s << indent << "state: ";
    s << std::endl;
    Printer< ::my_msgs::state_<ContainerAllocator> >::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RT_SET_STATEREQUEST_H
