// Generated by gencpp from file deepbuilder/rt_set_actionRequest.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_RT_SET_ACTIONREQUEST_H
#define DEEPBUILDER_MESSAGE_RT_SET_ACTIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <my_msgs/action.h>

namespace deepbuilder
{
template <class ContainerAllocator>
struct rt_set_actionRequest_
{
  typedef rt_set_actionRequest_<ContainerAllocator> Type;

  rt_set_actionRequest_()
    : controller()
    , action()  {
    }
  rt_set_actionRequest_(const ContainerAllocator& _alloc)
    : controller(_alloc)
    , action(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _controller_type;
  _controller_type controller;

   typedef  ::my_msgs::action_<ContainerAllocator>  _action_type;
  _action_type action;





  typedef boost::shared_ptr< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct rt_set_actionRequest_

typedef ::deepbuilder::rt_set_actionRequest_<std::allocator<void> > rt_set_actionRequest;

typedef boost::shared_ptr< ::deepbuilder::rt_set_actionRequest > rt_set_actionRequestPtr;
typedef boost::shared_ptr< ::deepbuilder::rt_set_actionRequest const> rt_set_actionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'deepbuilder': ['/home/ros/deepbuilder/catkin_ws/src/deepbuilder/msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d06ec287625f49b9001c48a2d24b856";
  }

  static const char* value(const ::deepbuilder::rt_set_actionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d06ec287625f49bULL;
  static const uint64_t static_value2 = 0x9001c48a2d24b856ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/rt_set_actionRequest";
  }

  static const char* value(const ::deepbuilder::rt_set_actionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string controller\n\
my_msgs/action action\n\
\n\
================================================================================\n\
MSG: my_msgs/action\n\
string id\n\
float32 A0\n\
float32 A1\n\
float32 A2\n\
float32 A3\n\
float32 A4\n\
float32 A5\n\
";
  }

  static const char* value(const ::deepbuilder::rt_set_actionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controller);
      stream.next(m.action);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct rt_set_actionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::rt_set_actionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::rt_set_actionRequest_<ContainerAllocator>& v)
  {
    s << indent << "controller: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.controller);
    s << indent << "action: ";
    s << std::endl;
    Printer< ::my_msgs::action_<ContainerAllocator> >::stream(s, indent + "  ", v.action);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_RT_SET_ACTIONREQUEST_H
