// Generated by gencpp from file deepbuilder/se_adjust_resolution.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_SE_ADJUST_RESOLUTION_H
#define DEEPBUILDER_MESSAGE_SE_ADJUST_RESOLUTION_H

#include <ros/service_traits.h>


#include <deepbuilder/se_adjust_resolutionRequest.h>
#include <deepbuilder/se_adjust_resolutionResponse.h>


namespace deepbuilder
{

struct se_adjust_resolution
{

typedef se_adjust_resolutionRequest Request;
typedef se_adjust_resolutionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct se_adjust_resolution
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::se_adjust_resolution > {
  static const char* value()
  {
    return "c347af19957c4bfd6fa7272ca95ca3d6";
  }

  static const char* value(const ::deepbuilder::se_adjust_resolution&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::se_adjust_resolution > {
  static const char* value()
  {
    return "deepbuilder/se_adjust_resolution";
  }

  static const char* value(const ::deepbuilder::se_adjust_resolution&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::se_adjust_resolutionRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::se_adjust_resolution > 
template<>
struct MD5Sum< ::deepbuilder::se_adjust_resolutionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_adjust_resolution >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_resolutionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_adjust_resolutionRequest> should match 
// service_traits::DataType< ::deepbuilder::se_adjust_resolution > 
template<>
struct DataType< ::deepbuilder::se_adjust_resolutionRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_adjust_resolution >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_resolutionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::se_adjust_resolutionResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::se_adjust_resolution > 
template<>
struct MD5Sum< ::deepbuilder::se_adjust_resolutionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_adjust_resolution >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_resolutionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_adjust_resolutionResponse> should match 
// service_traits::DataType< ::deepbuilder::se_adjust_resolution > 
template<>
struct DataType< ::deepbuilder::se_adjust_resolutionResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_adjust_resolution >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_resolutionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_SE_ADJUST_RESOLUTION_H
