// Generated by gencpp from file deepbuilder/se_adjust_fieldsize_x.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_SE_ADJUST_FIELDSIZE_X_H
#define DEEPBUILDER_MESSAGE_SE_ADJUST_FIELDSIZE_X_H

#include <ros/service_traits.h>


#include <deepbuilder/se_adjust_fieldsize_xRequest.h>
#include <deepbuilder/se_adjust_fieldsize_xResponse.h>


namespace deepbuilder
{

struct se_adjust_fieldsize_x
{

typedef se_adjust_fieldsize_xRequest Request;
typedef se_adjust_fieldsize_xResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct se_adjust_fieldsize_x
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::se_adjust_fieldsize_x > {
  static const char* value()
  {
    return "c347af19957c4bfd6fa7272ca95ca3d6";
  }

  static const char* value(const ::deepbuilder::se_adjust_fieldsize_x&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::se_adjust_fieldsize_x > {
  static const char* value()
  {
    return "deepbuilder/se_adjust_fieldsize_x";
  }

  static const char* value(const ::deepbuilder::se_adjust_fieldsize_x&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_xRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_x > 
template<>
struct MD5Sum< ::deepbuilder::se_adjust_fieldsize_xRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_adjust_fieldsize_x >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_xRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_xRequest> should match 
// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_x > 
template<>
struct DataType< ::deepbuilder::se_adjust_fieldsize_xRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_adjust_fieldsize_x >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_xRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_xResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_x > 
template<>
struct MD5Sum< ::deepbuilder::se_adjust_fieldsize_xResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_adjust_fieldsize_x >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_xResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_xResponse> should match 
// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_x > 
template<>
struct DataType< ::deepbuilder::se_adjust_fieldsize_xResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_adjust_fieldsize_x >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_xResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_SE_ADJUST_FIELDSIZE_X_H
