// Generated by gencpp from file deepbuilder/se_adjust_fieldsize_y.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_SE_ADJUST_FIELDSIZE_Y_H
#define DEEPBUILDER_MESSAGE_SE_ADJUST_FIELDSIZE_Y_H

#include <ros/service_traits.h>


#include <deepbuilder/se_adjust_fieldsize_yRequest.h>
#include <deepbuilder/se_adjust_fieldsize_yResponse.h>


namespace deepbuilder
{

struct se_adjust_fieldsize_y
{

typedef se_adjust_fieldsize_yRequest Request;
typedef se_adjust_fieldsize_yResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct se_adjust_fieldsize_y
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::se_adjust_fieldsize_y > {
  static const char* value()
  {
    return "c347af19957c4bfd6fa7272ca95ca3d6";
  }

  static const char* value(const ::deepbuilder::se_adjust_fieldsize_y&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::se_adjust_fieldsize_y > {
  static const char* value()
  {
    return "deepbuilder/se_adjust_fieldsize_y";
  }

  static const char* value(const ::deepbuilder::se_adjust_fieldsize_y&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_yRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_y > 
template<>
struct MD5Sum< ::deepbuilder::se_adjust_fieldsize_yRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_adjust_fieldsize_y >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_yRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_yRequest> should match 
// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_y > 
template<>
struct DataType< ::deepbuilder::se_adjust_fieldsize_yRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_adjust_fieldsize_y >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_yRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_yResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::se_adjust_fieldsize_y > 
template<>
struct MD5Sum< ::deepbuilder::se_adjust_fieldsize_yResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_adjust_fieldsize_y >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_yResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_yResponse> should match 
// service_traits::DataType< ::deepbuilder::se_adjust_fieldsize_y > 
template<>
struct DataType< ::deepbuilder::se_adjust_fieldsize_yResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_adjust_fieldsize_y >::value();
  }
  static const char* value(const ::deepbuilder::se_adjust_fieldsize_yResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_SE_ADJUST_FIELDSIZE_Y_H
