// Generated by gencpp from file deepbuilder/se_collect_stateRequest.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_SE_COLLECT_STATEREQUEST_H
#define DEEPBUILDER_MESSAGE_SE_COLLECT_STATEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace deepbuilder
{
template <class ContainerAllocator>
struct se_collect_stateRequest_
{
  typedef se_collect_stateRequest_<ContainerAllocator> Type;

  se_collect_stateRequest_()
    : poses()
    , pairs()
    , pair_lengths()  {
    }
  se_collect_stateRequest_(const ContainerAllocator& _alloc)
    : poses(_alloc)
    , pairs(_alloc)
    , pair_lengths(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _poses_type;
  _poses_type poses;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _pairs_type;
  _pairs_type pairs;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _pair_lengths_type;
  _pair_lengths_type pair_lengths;





  typedef boost::shared_ptr< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> const> ConstPtr;

}; // struct se_collect_stateRequest_

typedef ::deepbuilder::se_collect_stateRequest_<std::allocator<void> > se_collect_stateRequest;

typedef boost::shared_ptr< ::deepbuilder::se_collect_stateRequest > se_collect_stateRequestPtr;
typedef boost::shared_ptr< ::deepbuilder::se_collect_stateRequest const> se_collect_stateRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace deepbuilder

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'shape_msgs': ['/opt/ros/kinetic/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/kinetic/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/kinetic/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/kinetic/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/kinetic/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'rosbridge_msgs': ['/opt/ros/kinetic/share/rosbridge_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0a2d8bbcfc4f9ed8bd886393d1b75193";
  }

  static const char* value(const ::deepbuilder::se_collect_stateRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0a2d8bbcfc4f9ed8ULL;
  static const uint64_t static_value2 = 0xbd886393d1b75193ULL;
};

template<class ContainerAllocator>
struct DataType< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "deepbuilder/se_collect_stateRequest";
  }

  static const char* value(const ::deepbuilder::se_collect_stateRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] poses\n\
int32[] pairs\n\
int32[] pair_lengths\n\
";
  }

  static const char* value(const ::deepbuilder::se_collect_stateRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.poses);
      stream.next(m.pairs);
      stream.next(m.pair_lengths);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct se_collect_stateRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::deepbuilder::se_collect_stateRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::deepbuilder::se_collect_stateRequest_<ContainerAllocator>& v)
  {
    s << indent << "poses[]" << std::endl;
    for (size_t i = 0; i < v.poses.size(); ++i)
    {
      s << indent << "  poses[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.poses[i]);
    }
    s << indent << "pairs[]" << std::endl;
    for (size_t i = 0; i < v.pairs.size(); ++i)
    {
      s << indent << "  pairs[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pairs[i]);
    }
    s << indent << "pair_lengths[]" << std::endl;
    for (size_t i = 0; i < v.pair_lengths.size(); ++i)
    {
      s << indent << "  pair_lengths[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pair_lengths[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_SE_COLLECT_STATEREQUEST_H
