// Generated by gencpp from file deepbuilder/se_collect_tags.msg
// DO NOT EDIT!


#ifndef DEEPBUILDER_MESSAGE_SE_COLLECT_TAGS_H
#define DEEPBUILDER_MESSAGE_SE_COLLECT_TAGS_H

#include <ros/service_traits.h>


#include <deepbuilder/se_collect_tagsRequest.h>
#include <deepbuilder/se_collect_tagsResponse.h>


namespace deepbuilder
{

struct se_collect_tags
{

typedef se_collect_tagsRequest Request;
typedef se_collect_tagsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct se_collect_tags
} // namespace deepbuilder


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::deepbuilder::se_collect_tags > {
  static const char* value()
  {
    return "6a3bb97297abf73607870ea61a5466bd";
  }

  static const char* value(const ::deepbuilder::se_collect_tags&) { return value(); }
};

template<>
struct DataType< ::deepbuilder::se_collect_tags > {
  static const char* value()
  {
    return "deepbuilder/se_collect_tags";
  }

  static const char* value(const ::deepbuilder::se_collect_tags&) { return value(); }
};


// service_traits::MD5Sum< ::deepbuilder::se_collect_tagsRequest> should match 
// service_traits::MD5Sum< ::deepbuilder::se_collect_tags > 
template<>
struct MD5Sum< ::deepbuilder::se_collect_tagsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_collect_tags >::value();
  }
  static const char* value(const ::deepbuilder::se_collect_tagsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_collect_tagsRequest> should match 
// service_traits::DataType< ::deepbuilder::se_collect_tags > 
template<>
struct DataType< ::deepbuilder::se_collect_tagsRequest>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_collect_tags >::value();
  }
  static const char* value(const ::deepbuilder::se_collect_tagsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::deepbuilder::se_collect_tagsResponse> should match 
// service_traits::MD5Sum< ::deepbuilder::se_collect_tags > 
template<>
struct MD5Sum< ::deepbuilder::se_collect_tagsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::deepbuilder::se_collect_tags >::value();
  }
  static const char* value(const ::deepbuilder::se_collect_tagsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::deepbuilder::se_collect_tagsResponse> should match 
// service_traits::DataType< ::deepbuilder::se_collect_tags > 
template<>
struct DataType< ::deepbuilder::se_collect_tagsResponse>
{
  static const char* value()
  {
    return DataType< ::deepbuilder::se_collect_tags >::value();
  }
  static const char* value(const ::deepbuilder::se_collect_tagsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DEEPBUILDER_MESSAGE_SE_COLLECT_TAGS_H
