// Generated by gencpp from file my_msgs/state.msg
// DO NOT EDIT!


#ifndef MY_MSGS_MESSAGE_STATE_H
#define MY_MSGS_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>
#include <geometry_msgs/Pose.h>

namespace my_msgs
{
template <class ContainerAllocator>
struct state_
{
  typedef state_<ContainerAllocator> Type;

  state_()
    : action_id()
    , out_of_reach(false)
    , self_collision(false)
    , last_tcp()
    , fastest_box(0)
    , highest_box(0)
    , current_height(0.0)
    , box_poses()  {
    }
  state_(const ContainerAllocator& _alloc)
    : action_id(_alloc)
    , out_of_reach(false)
    , self_collision(false)
    , last_tcp(_alloc)
    , fastest_box(0)
    , highest_box(0)
    , current_height(0.0)
    , box_poses(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _action_id_type;
  _action_id_type action_id;

   typedef uint8_t _out_of_reach_type;
  _out_of_reach_type out_of_reach;

   typedef uint8_t _self_collision_type;
  _self_collision_type self_collision;

   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _last_tcp_type;
  _last_tcp_type last_tcp;

   typedef int32_t _fastest_box_type;
  _fastest_box_type fastest_box;

   typedef int32_t _highest_box_type;
  _highest_box_type highest_box;

   typedef float _current_height_type;
  _current_height_type current_height;

   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _box_poses_type;
  _box_poses_type box_poses;





  typedef boost::shared_ptr< ::my_msgs::state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_msgs::state_<ContainerAllocator> const> ConstPtr;

}; // struct state_

typedef ::my_msgs::state_<std::allocator<void> > state;

typedef boost::shared_ptr< ::my_msgs::state > statePtr;
typedef boost::shared_ptr< ::my_msgs::state const> stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_msgs::state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_msgs::state_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace my_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'my_msgs': ['/home/ros/deepbuilder/catkin_ws/src/my_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_msgs::state_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_msgs::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_msgs::state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_msgs::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "72cea1bd08eaaeaa5fb310c31bb88005";
  }

  static const char* value(const ::my_msgs::state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x72cea1bd08eaaeaaULL;
  static const uint64_t static_value2 = 0x5fb310c31bb88005ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_msgs::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_msgs/state";
  }

  static const char* value(const ::my_msgs::state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_msgs::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string action_id\n\
bool out_of_reach\n\
bool self_collision\n\
geometry_msgs/Pose last_tcp\n\
int32 fastest_box\n\
int32 highest_box\n\
float32 current_height\n\
geometry_msgs/Pose[] box_poses\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::my_msgs::state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_msgs::state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.action_id);
      stream.next(m.out_of_reach);
      stream.next(m.self_collision);
      stream.next(m.last_tcp);
      stream.next(m.fastest_box);
      stream.next(m.highest_box);
      stream.next(m.current_height);
      stream.next(m.box_poses);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_msgs::state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_msgs::state_<ContainerAllocator>& v)
  {
    s << indent << "action_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.action_id);
    s << indent << "out_of_reach: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.out_of_reach);
    s << indent << "self_collision: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.self_collision);
    s << indent << "last_tcp: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.last_tcp);
    s << indent << "fastest_box: ";
    Printer<int32_t>::stream(s, indent + "  ", v.fastest_box);
    s << indent << "highest_box: ";
    Printer<int32_t>::stream(s, indent + "  ", v.highest_box);
    s << indent << "current_height: ";
    Printer<float>::stream(s, indent + "  ", v.current_height);
    s << indent << "box_poses[]" << std::endl;
    for (size_t i = 0; i < v.box_poses.size(); ++i)
    {
      s << indent << "  box_poses[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.box_poses[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_MSGS_MESSAGE_STATE_H
